development:
  adapter: mysql2
  encoding: utf8
  database: glance_dev
  username: root
  password: ''

test: &test
  adapter: mysql2
  encoding: utf8
  database: glance_test
  username: root
  password: ''

production:
  adapter: mysql2
  encoding: utf8
  database: glance_prod
  username: root
  password: ''

cucumber:
  <<: *test
